# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Print funksiyasini taqiqlash (debug uchun loglardan foydalanish kerak)
    avoid_print: true
    
    # Qo'shtirnoq (") o'rniga bittalik tirnoq (') ishlatishni afzal ko'rish
    prefer_single_quotes: true
    
    # Iloji bor joyda const konstruktorlardan foydalanish (ishlash tezligi uchun)
    prefer_const_constructors: true
    
    # Keraksiz 'new' so'zini ishlatmaslik
    unnecessary_new: true
    
    # const ishlatish mumkin bo'lgan joyda const ishlatishni talab qilish
    prefer_const_literals_to_create_immutables: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options